// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"60","Fade In Time":"60","Wait Time":"80"}},
{"name":"OrangeHud","status":true,"description":"<OrangeHud> 2.1 - Creates a custom HUD based on the params","parameters":{"DefaultFontFace":"Verdana","DefaultFontSize":"18","DefaultFontColor":"#FFFFFF","DefaultFontItalic":"false","HudWidth":"300","HudHeight":"180","HudX":"0","HudY":"0","HudOpacity":"255","SwitchId":"0","WindowMargin":"4","WindowPadding":"18","ShowOnMap":"true","ShowOnBattle":"false","ShowOnMenu":"false","ShowOnTitle":"false","ShowUnderTintLayer":"false","AutoRefresh":"true"}},
{"name":"OrangeHudFacePicture","status":true,"description":"Draws a character's face on the OrangeHud","parameters":{"GroupName":"main","ActorIndex":"0","SwitchId":"0","X":"","Y":"","VariableX":"0","VariableY":"0"}},
{"name":"OrangeHudActorStatusHP","status":true,"description":"Adds a new line to Orange Hud to display an actor's status","parameters":{"GroupName":"main","Pattern":"HP: <hp>","ActorIndex":"0","SwitchId":"0","X":"150","Y":"0","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":""}},
{"name":"OrangeHudActorStatusMP","status":true,"description":"Adds a new line to Orange Hud to display an actor's status","parameters":{"GroupName":"main","Pattern":"MP: <mhp>","ActorIndex":"0","SwitchId":"0","X":"150","Y":"30","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":""}},
{"name":"OrangeHudActorStatusEXP","status":true,"description":"Adds a new line to Orange Hud to display an actor's status","parameters":{"GroupName":"main","Pattern":"Nível: <level>","ActorIndex":"0","SwitchId":"0","X":"150","Y":"60","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":""}}
];
